---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: my-deployment
spec:
   replicas: 2
   selector:
      matchLabels:
         env: dev
   template:
      metadata:
         labels:
           env: dev
      spec:
         containers:
           - name: app-container
             image: shaikmustafa/dm
             ports:
              - containerPort: 80
